[edge_nodes]
rasp5node.local ansible_user=admin

[edge_nodes:vars]
ansible_connection=ssh
# Use the full absolute path to eliminate path expansion errors
ansible_ssh_private_key_file=/Users/stamencho.bogdanovski/.ssh/rasp5node
# Strip out the Mac locale noise completely
ansible_ssh_common_args='-o IdentitiesOnly=yes -o SendEnv="-LC_*" -o SetEnv="LANG=en_US.UTF-8" -o SetEnv="LC_ALL=en_US.UTF-8"'